export interface FAQItem {
  question: string;
  answer: string;
}

export interface SpecItem {
  label: string;
  value: string;
}

export interface ServiceDetail {
  slug: string;
  name: string;
  category: "safety-nets" | "invisible-grills" | "cloth-hangers";
  categoryName: string;
  title: string;
  description: string;
  longDescription: string;
  aiOverview: string;
  image: string;
  supportingImages: string[];
  gallery: string[];
  beforeImage: string;
  afterImage: string;
  benefits: string[];
  specsTable: SpecItem[];
  faqs: FAQItem[];
}

// Generates 12 in-depth, original FAQs for each safety service
function generateFAQsForService(serviceName: string, category: string): FAQItem[] {
  return [
    {
      question: `What is the pricing model for ${serviceName} in Chennai?`,
      answer: "Pricing is calculated straightforwardly per square foot of coverage area, considering the installation elevation, bracket type, and specific hardware requirements. We provide a completely free doorstep measurement and written quotation.",
    },
    {
      question: `What warranty coverage accompanies ${serviceName} from Ram Enterprises?`,
      answer: category === "invisible-grills"
        ? "All SS316 marine invisible grill installations come with an extensive 10+ Year Anti-Rust & Tension Assurance Guarantee protecting against coastal corrosion and cable sag."
        : "All installations come with a comprehensive 3 to 5 Year Service & Replacement Guarantee protecting against sunlight embrittlement, tension sag, and material corrosion.",
    },
    {
      question: `How long does our technician crew take to complete the installation?`,
      answer: `Standard apartment installations of ${serviceName} are completed within 2 to 4 hours with minimum disruption to your day, complete with clean drill dust vacuuming.`,
    },
    {
      question: `How does ${serviceName} hold up against Chennai's sea air and coastal humidity?`,
      answer: `We configure each installation specifically for Chennai's coastal environment using UV-stabilized copolymer netting and marine-grade SS316 stainless steel fixtures that never rust or degrade in saline moisture.`,
    },
    {
      question: `Is the on-site inspection truly complimentary?`,
      answer: `Yes, our technician team visits your home in Chennai free of charge to measure the balconies or windows, present physical material samples, and answer all questions with zero obligation.`,
    },
    {
      question: `How do you anchor into balconies without causing wall cracks?`,
      answer: "We utilize industrial diamond-core rotary equipment and high-tensile stainless expansion fasteners to anchor directly into concrete lintels, ensuring tremendous load resistance while preserving wall plaster integrity.",
    },
    {
      question: `How dependable is ${serviceName} for high-floor child protection?`,
      answer: `Engineered with multi-strand knotted load resistance, ${serviceName} acts as an infallible physical barrier, eliminating fall hazards across high-rise balconies, stair voids, and open windows.`,
    },
    {
      question: `Can pets claw or bite through ${serviceName}?`,
      answer: category === "invisible-grills" 
        ? "Marine SS316 stainless cables are totally impervious to clawing or chewing by cats and dogs, delivering impenetrable high-rise safety for animal lovers."
        : "Our pet-defense nets use heavy-gauge knotted polymers with reinforced mesh density that withstands scratching and pet weight effortlessly.",
    },
    {
      question: `Will ${serviceName} block natural ventilation or daylight?`,
      answer: category === "invisible-grills"
        ? "Invisible grills maintain an open 180-degree panoramic sightline with slim 2.0mm-3.0mm aircraft-grade cables, keeping your living space airy, sunlit, and modern."
        : "Our translucent mesh is engineered to blend seamlessly into background architecture while preserving 100% natural breeze and sunlight.",
    },
    {
      question: `Are your field technicians certified for high-rise exterior installations?`,
      answer: `Yes, every Ram Enterprises installer is trained in rope-access maneuvers, full-body safety harness operations, and high-altitude anchor tensioning protocol.`,
    },
    {
      question: `What routine maintenance is expected for ${serviceName}?`,
      answer: "No specialized maintenance is necessary. A brief rinse with water or gentle wipe down with a damp cloth keeps your netting or stainless steel wires pristine for years.",
    },
    {
      question: `How can I book an urgent installation appointment with Ram Enterprises?`,
      answer: "Call our direct helpline at +91 90305 05683, send a WhatsApp message to our rapid desk, or submit our online inquiry form for same-day booking.",
    },
  ];
}

export const servicesData: Record<string, ServiceDetail> = {
  // ----------------------------------------------------
  // Safety Nets (10 Services)
  // ----------------------------------------------------
  "balcony-safety-nets": {
    slug: "balcony-safety-nets",
    name: "Balcony Safety Nets",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Balcony Safety Nets Installation in Chennai | Ram Enterprises",
    description: "Guard your balcony against accidental falls with heavy-gauge, UV-stabilized copolymer netting. Certified high-rise protection across Adyar, Velachery, Anna Nagar, and all of Chennai.",
    longDescription: "Ram Enterprises specializes in robust balcony safety netting installations across Chennai's high-rise communities. Fabricated from 100% virgin high-density polymer compounds with embedded UV stabilizers, our netting easily endures Chennai's harsh summer heat and intense monsoon downpours, keeping children and pets secure without obstructing your city or ocean view.",
    aiOverview: "Ram Enterprises Balcony Safety Nets provide tested high-tensile fall containment utilizing weather-fortified virgin polymer mesh. Tailored for multi-story apartment towers across Chennai, our setups guarantee reliable safety with uninterrupted natural breeze.",
    image: "/images/hero/balconysafetynet.jpg",
    supportingImages: [
      "/images/materials/Balconynetwork.jpeg",
      "/images/hero/safetynets2.jpg",
      "/images/hero/safetynets.webp",
      "/images/services/child.webp",
    ],
    gallery: [
      "/images/hero/balconysafetynet.jpg",
      "/images/materials/Balconynetwork.jpeg",
      "/images/hero/safetynets2.jpg",
      "/images/hero/safetynets.webp",
      "/images/services/child.webp",
      "/images/materials/FactoryNets.jpeg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/materials/Balconynetwork.jpeg",
    benefits: [
      "Certified point-load capacity exceeding 140kg per knot",
      "100% virgin HDPE with heavy UV stabilizers for 10+ year longevity",
      "Translucent micro-mesh that preserves sunlight and fresh airflow",
      "Marine-grade 304/316 stainless anchor hardware that resists rust",
      "Custom perimeter border rope tensioned to eliminate all gaps",
      "Official 5-Year Replacement Warranty card issued upon completion",
    ],
    specsTable: [
      { label: "Material Composition", value: "Virgin UV-Stabilized HDPE Copolymer" },
      { label: "Mesh Aperture Size", value: "30mm x 30mm Square Knotted Mesh" },
      { label: "Cord Diameter", value: "1.5mm to 2.5mm Multi-Strand Braided" },
      { label: "Tensile Breaking Strength", value: "140+ kg per single mesh intersection" },
      { label: "Anchoring Hardware", value: "SS304 Marine Expansion Hooks & Eye-Bolts" },
      { label: "Anchor Interval Spacing", value: "15 cm (6 inches) uniform perimeter pitch" },
      { label: "Weather Resistance", value: "Resistant to UV-C, saline air & torrential rain" },
      { label: "Warranty Term", value: "5 Years Full Replacement Warranty" },
    ],
    faqs: generateFAQsForService("Balcony Safety Nets", "safety-nets"),
  },

  "children-safety-nets": {
    slug: "children-safety-nets",
    name: "Children Safety Nets",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Child Safety Nets for Balconies & Windows | Ram Enterprises Chennai",
    description: "Ultra-secure childproof fall containment nets engineered for high-rise balconies, open windows, and stairwell voids in Chennai apartments.",
    longDescription: "Give your family unconditional peace of mind with Ram Enterprises children safety netting. We fit high-density knotted barriers precisely along balcony railings, open window frames, and staircase banisters, transforming high-risk gaps into secure, child-friendly spaces where little ones can play freely without danger of accidental falls.",
    aiOverview: "Ram Enterprises Child Safety Nets deliver specialized high-tensile perimeter security for families residing in high-rise towers. Anchored with ultra-narrow pitch spacing, they completely seal dangerous railing intervals.",
    image: "/images/services/child.webp",
    supportingImages: [
      "/images/services/child.webp",
      "/images/hero/childrensafetynet.webp",
      "/images/materials/Balconynetwork.jpeg",
      "/images/hero/childrensafetygrill.jpg",
    ],
    gallery: [
      "/images/services/child.webp",
      "/images/services/child.webp",
      "/images/hero/childrensafetynet.webp",
      "/images/materials/Balconynetwork.jpeg",
      "/images/hero/childrensafetygrill.jpg",
      "/images/hero/safetynets2.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/services/child.webp",
    benefits: [
      "Custom 25mm tight mesh prevents toddler limbs from getting caught",
      "Exceeds 150kg impact load capacity to arrest sudden falls",
      "Anchored with dual-fastener stainless brackets for unyielding hold",
      "Soft, non-abrasive polymer cords safe for delicate children hands",
      "Allows clear outward visibility and full natural breeze into rooms",
      "Compliant with international apartment child safety standards",
    ],
    specsTable: [
      { label: "Mesh Density", value: "25mm x 25mm Childproof Knotted Square Mesh" },
      { label: "Cord Filament", value: "100% Virgin High-Tenacity Copolymer Nylon" },
      { label: "Cord Gauge", value: "2.0mm Heavy-Duty Multi-Filament Twine" },
      { label: "Impact Rating", value: "150+ kg sudden fall containment test certified" },
      { label: "Wall Anchor Pitch", value: "10 cm to 15 cm tight boundary spacing" },
      { label: "Anchor Type", value: "Heavy-Duty SS304 Concrete Sleeve Anchors" },
      { label: "Toxicity & Safety", value: "Non-toxic, lead-free, odorless synthetic compound" },
      { label: "Warranty Coverage", value: "5 Years Direct Workmanship & Material Warranty" },
    ],
    faqs: generateFAQsForService("Children Safety Nets", "safety-nets"),
  },

  "pet-safety-nets": {
    slug: "pet-safety-nets",
    name: "Pet Safety Nets",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Pet Safety Nets for Cats & Dogs | Ram Enterprises Chennai",
    description: "Claw-resistant, chew-tolerant safety netting designed to safeguard curious cats and active dogs from high-rise balcony falls across Chennai.",
    longDescription: "Curious cats and energetic dogs love looking through balcony railings and window ledges. Ram Enterprises pet safety nets feature reinforced multi-strand knotted braiding that resists claws, biting forces, and animal weight, preventing heartbreaking high-altitude slips while maintaining complete ventilation throughout your home.",
    aiOverview: "Ram Enterprises Pet Safety Nets are custom-tensioned containment barriers crafted from claw-resistant, reinforced synthetic nylon. They prevent domestic cats and dogs from slipping off high balconies.",
    image: "/images/hero/pet.jpg",
    supportingImages: [
      "/images/hero/pet.jpg",
      "/images/hero/safetynets.webp",
      "/images/materials/Balconynetwork.jpeg",
      "/images/services/shyampetinvisiblegrills.jpg",
    ],
    gallery: [
      "/images/hero/pet.jpg",
      "/images/hero/pet.jpg",
      "/images/hero/safetynets.webp",
      "/images/materials/Balconynetwork.jpeg",
      "/images/services/shyampetinvisiblegrills.jpg",
      "/images/hero/balconysafetynet.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/hero/pet.jpg",
    benefits: [
      "Fortified cross-weave resists aggressive cat scratching and dog clawing",
      "Dense 20mm-25mm mesh prevents kittens and puppies from squeezing through",
      "Chemical-free polymer formulation entirely non-toxic for licking or biting pets",
      "Rigid stainless perimeter wire prevents edge lifting and snout gaps",
      "100% weather-resistant under scorching coastal sunshine and heavy rain",
      "Backed by a dependable 5-Year Performance & Replacement Guarantee",
    ],
    specsTable: [
      { label: "Material Specification", value: "High-Tensile Reinforced Copolymer Polyethylene" },
      { label: "Mesh Opening", value: "20mm - 25mm Micro Aperture Webbing" },
      { label: "Cord Architecture", value: "Twisted Multi-Filament Claw-Resistant Core" },
      { label: "Load Capacity", value: "Tested up to 120 kg animal impact force" },
      { label: "Fastening Scheme", value: "Stainless Steel Eye-Bolts with Core Cable Lacing" },
      { label: "Toxicity Rating", value: "100% Food-Grade Safe Polymer Composition" },
      { label: "UV Durability", value: "UV Class 4 Stabilization (500kLy Resistance)" },
      { label: "Warranty Term", value: "5 Years Performance & Tear Guarantee" },
    ],
    faqs: generateFAQsForService("Pet Safety Nets", "safety-nets"),
  },

  "pigeon-safety-nets": {
    slug: "pigeon-safety-nets",
    name: "Pigeon Safety Nets",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Anti-Pigeon Safety Nets Installation in Chennai | Ram Enterprises",
    description: "Permanently exclude pigeons and pest birds from balconies, AC ledges, and utility shafts with discreet, humane anti-bird netting across Chennai.",
    longDescription: "Pigeons roosting around balconies, AC outdoor units, and building ducts cause severe hygiene risks, bad odors, and respiratory hazards. Ram Enterprises fits customized, translucent anti-pigeon netting that forms an impenetrable physical barrier, keeping your home spotless and bird-free without harming the birds in any way.",
    aiOverview: "Ram Enterprises Pigeon Safety Nets permanently block pigeons, sparrows, and pest birds from balcony ledges, AC compressors, and utility voids with humane, long-lasting mesh.",
    image: "/images/hero/pigeonnet.jpg",
    supportingImages: [
      "/images/hero/pigeonnet.jpg",
      "/images/hero/pigeonnet.jpg",
      "/images/hero/service-spikes.jpg",
      "/images/materials/Balconynetwork.jpeg",
    ],
    gallery: [
      "/images/hero/pigeonnet.jpg",
      "/images/hero/pigeonnet.jpg",
      "/images/hero/pigeonnet.jpg",
      "/images/hero/service-spikes.jpg",
      "/images/materials/Balconynetwork.jpeg",
      "/images/hero/safetynets2.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/hero/pigeonnet.jpg",
    benefits: [
      "100% humane bird exclusion with zero injury or distress to birds",
      "Translucent nylon monofilament mesh nearly invisible from ground level",
      "Eliminates disease-carrying bird droppings, foul smells, and noisy roosting",
      "Tailored cutouts around AC copper tubes and plumbing drain pipes",
      "UV-inhibited polymer that will not rot, sag, or embrittle under heat",
      "Fast same-day doorstep installation across all Chennai localities",
    ],
    specsTable: [
      { label: "Mesh Dimension", value: "25mm x 25mm (1 Inch) Square Bird Mesh" },
      { label: "Mesh Material", value: "UV-Stabilized Translucent Copolymer Monofilament" },
      { label: "Twine Diameter", value: "1.0mm - 1.2mm High-Tenacity Knotted String" },
      { label: "Visual Profile", value: "Transparent / Discreet White-Grey Aesthetic" },
      { label: "Fastening Hardware", value: "Stainless Steel Anchor Hooks & Galvanized Cable" },
      { label: "Humane Compliance", value: "100% Animal Welfare Friendly Barrier" },
      { label: "Longevity", value: "8 to 10+ Years under harsh coastal sun" },
      { label: "Warranty", value: "5 Years Direct Replacement Warranty" },
    ],
    faqs: generateFAQsForService("Pigeon Safety Nets", "safety-nets"),
  },

  "monkey-safety-nets": {
    slug: "monkey-safety-nets",
    name: "Monkey Safety Nets",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Heavy-Duty Monkey Safety Nets in Chennai | Ram Enterprises",
    description: "Extra-thick, reinforced monkey defense netting engineered to stop aggressive monkey intrusions into balconies and terraces in Chennai.",
    longDescription: "In areas bordering hill tracts, open parks, and temple corridors across Chennai, monkeys frequently raid residential balconies, destroy potted plants, and tear drying laundry. Ram Enterprises installs extra-thick, steel-reinforced monkey defense netting secured with industrial expansion anchors that safely keeps troops off your property.",
    aiOverview: "Ram Enterprises Monkey Safety Nets utilize extra-thick high-tensile cords and heavy steel expansion hooks to resist monkey climbing, pulling, and biting forces.",
    image: "/images/hero/monkeysafetynet.webp",
    supportingImages: [
      "/images/hero/monkeysafetynet.webp",
      "/images/hero/safetynets.webp",
      "/images/materials/FactoryNets.jpeg",
      "/images/materials/Balconynetwork.jpeg",
    ],
    gallery: [
      "/images/hero/monkeysafetynet.webp",
      "/images/hero/monkeysafetynet.webp",
      "/images/hero/safetynets.webp",
      "/images/materials/FactoryNets.jpeg",
      "/images/materials/Balconynetwork.jpeg",
      "/images/hero/safetynets2.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/hero/monkeysafetynet.webp",
    benefits: [
      "Extra-thick 2.5mm - 3.0mm multi-strand twine resists severe biting and pulling",
      "Steel-core perimeter boundary rope prevents edge lifting or stretching",
      "Heavy industrial concrete anchors withstand bodyweight of multiple adult monkeys",
      "Safeguards terrace gardens, clothes drying lines, and children play zones",
      "Weatherproof polymer will not corrode in monsoons or fade under the sun",
      "Supported by Ram Enterprises comprehensive 5-Year Heavy-Duty Warranty",
    ],
    specsTable: [
      { label: "Cord Gauge", value: "2.5mm - 3.0mm Fortified High-Gauge Braided Poly" },
      { label: "Mesh Pitch", value: "40mm x 40mm Heavy Knotted Grid" },
      { label: "Tensile Threshold", value: "200+ kg individual mesh breaking strength" },
      { label: "Perimeter System", value: "Stainless Steel Wire Rope Core Boundary" },
      { label: "Wall Fasteners", value: "10mm Heavy Expansion Concrete Eye-Bolts" },
      { label: "Weather Resistance", value: "UV Protected Class 5 Extreme Outdoor Grade" },
      { label: "Safe & Humane", value: "Repels monkeys without electric shocks or sharp cuts" },
      { label: "Warranty", value: "5 Years Heavy-Duty Assurance Guarantee" },
    ],
    faqs: generateFAQsForService("Monkey Safety Nets", "safety-nets"),
  },

  "cricket-nets": {
    slug: "cricket-nets",
    name: "Cricket Practice Nets",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Cricket Practice Nets & Pitch Enclosures | Ram Enterprises Chennai",
    description: "Custom batting cages and terrace bowling enclosures engineered to absorb high-velocity leather ball impacts across Chennai sports facilities.",
    longDescription: "Elevate your cricket training safely with custom batting cages and pitch enclosures from Ram Enterprises. We fabricate high-impact netting that absorbs hard leather ball strikes while protecting surrounding glass windows, vehicles, and neighboring homes on rooftop terraces and sports academies.",
    aiOverview: "Ram Enterprises Cricket Nets provide impact-absorbing ball confinement enclosures for terrace rooftops, turf clubs, and sports training facilities across Chennai.",
    image: "/images/hero/cricketpracticenet.jpg",
    supportingImages: [
      "/images/materials/BoxCricketnet.jpeg",
      "/images/hero/cricket.jpeg",
      "/images/materials/FactoryNets.jpeg",
      "/images/hero/sports-safety.webp",
    ],
    gallery: [
      "/images/hero/cricketpracticenet.jpg",
      "/images/materials/BoxCricketnet.jpeg",
      "/images/hero/cricket.jpeg",
      "/images/materials/FactoryNets.jpeg",
      "/images/hero/sports-safety.webp",
      "/images/materials/Balconynetwork.jpeg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/materials/BoxCricketnet.jpeg",
    benefits: [
      "Engineered to withstand 150+ km/h leather cricket ball strikes without tear",
      "Tailor-made dimensions for single-lane, dual-lane, or full box cricket turf setups",
      "Includes structural GI or MS pipe framing with anti-corrosion primer coating",
      "UV-stabilized monofilament mesh designed for rooftop open-air exposure",
      "Overhead roof netting prevents errant sixes from damaging neighboring properties",
      "Installed by dedicated sports netting engineers with 5-Year Durability Guarantee",
    ],
    specsTable: [
      { label: "Mesh Pitch", value: "40mm - 45mm Square Impact Aperture" },
      { label: "Cord Composition", value: "High-Density Braided Polyethylene Twine" },
      { label: "Twine Thickness", value: "2.0mm to 3.5mm Heavy Gauge Sport Core" },
      { label: "Impact Absorption", value: "Rated for 160 km/h leather ball repetitive strikes" },
      { label: "Framing Options", value: "Galvanized Iron (GI) / Structural MS Pipe Framework" },
      { label: "Tensioning Mechanism", value: "Turnbuckles & High-Tension Steel Core Wire" },
      { label: "UV Protection", value: "100% Outdoor UV Stabilized Compound" },
      { label: "Warranty Period", value: "5 Years Structural & Netting Warranty" },
    ],
    faqs: generateFAQsForService("Cricket Practice Nets", "safety-nets"),
  },

  "sports-nets": {
    slug: "sports-nets",
    name: "Sports Netting",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Sports Netting & Box Enclosures in Chennai | Ram Enterprises",
    description: "Complete perimeter ball-stop netting for football turfs, badminton courts, tennis arenas, and school sports grounds throughout Chennai.",
    longDescription: "Ram Enterprises provides comprehensive sports perimeter netting solutions tailored for indoor and outdoor turf complexes, commercial arenas, and schools. We manufacture and install impact-absorbing boundary netting that keeps balls confined within court limits while guaranteeing spectator and property safety.",
    aiOverview: "Ram Enterprises Sports Nets deliver heavy-gauge ball-stop containment for multi-sport turfs, futsal courts, and athletic facilities across Chennai.",
    image: "/images/hero/sports-safety.webp",
    supportingImages: [
      "/images/materials/BoxCricketnet.jpeg",
      "/images/materials/BoxCricketnet.jpeg",
      "/images/hero/cricketpracticenet.jpg",
      "/images/materials/FactoryNets.jpeg",
    ],
    gallery: [
      "/images/hero/sports-safety.webp",
      "/images/materials/BoxCricketnet.jpeg",
      "/images/materials/BoxCricketnet.jpeg",
      "/images/hero/cricketpracticenet.jpg",
      "/images/materials/FactoryNets.jpeg",
      "/images/hero/cricket.jpeg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/materials/BoxCricketnet.jpeg",
    benefits: [
      "Custom height netting up to 40+ feet for football, futsal, and volleyball courts",
      "Heavy-duty impact absorption prevents rebound injuries and lost equipment",
      "All-weather synthetic construction resists torrential rains and coastal sun",
      "Sturdy steel cable tensioning ensures zero sagging over large spans",
      "Bulk institutional rates for schools, residential clubhouses, and turf venues",
      "Certified installation backed by 5-Year Comprehensive Warranty",
    ],
    specsTable: [
      { label: "Mesh Aperture", value: "40mm / 50mm / 75mm depending on sport profile" },
      { label: "Material Compound", value: "Virgin High-Density Polymer with UV Stabilizers" },
      { label: "Cord Strength", value: "160+ kg tensile limit per knotted intersection" },
      { label: "Height Capability", value: "Custom engineered spans up to 45 feet vertical" },
      { label: "Suspension Hardware", value: "Stainless Steel Turnbuckles & Guy Wire Rigging" },
      { label: "Safety Rating", value: "Certified spectator and property perimeter barrier" },
      { label: "Outdoor Endurance", value: "10+ Years under open tropical weather" },
      { label: "Warranty Term", value: "5 Years Complete System Guarantee" },
    ],
    faqs: generateFAQsForService("Sports Netting", "safety-nets"),
  },

  "construction-safety-nets": {
    slug: "construction-safety-nets",
    name: "Construction Safety Nets",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Construction Safety & Debris Netting in Chennai | Ram Enterprises",
    description: "Certified fall arrest personnel netting and high-density debris containment mesh for building contractors and multi-story sites across Chennai.",
    longDescription: "Workplace safety on construction sites is indispensable. Ram Enterprises equips multi-story commercial and residential construction projects with certified heavy-duty personnel fall-arrest netting and micro-debris containment mesh, preventing tragic worker falls and securing pedestrians below.",
    aiOverview: "Ram Enterprises Construction Safety Nets supply certified personnel fall catch barriers and fine debris mesh for builders and real estate contractors across Chennai.",
    image: "/images/hero/constructionnet.webp",
    supportingImages: [
      "/images/hero/constructionnet.webp",
      "/images/materials/FactoryNets.jpeg",
      "/images/hero/safetynets.webp",
      "/images/materials/Balconynetwork.jpeg",
    ],
    gallery: [
      "/images/hero/constructionnet.webp",
      "/images/hero/constructionnet.webp",
      "/images/materials/FactoryNets.jpeg",
      "/images/hero/safetynets.webp",
      "/images/materials/Balconynetwork.jpeg",
      "/images/hero/safetynets2.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/hero/constructionnet.webp",
    benefits: [
      "Complies with rigorous OSHA and Indian Safety Standard construction codes",
      "Dual-layer system: heavy fall-arrest base net with fine debris overlay",
      "Rated to catch falling workers up to 300+ kg impact load from 6 meters",
      "Flame-retardant and heavy chemical-resistant polymer formulations",
      "Flexible tie-off rigging compatible with scaffolding, structural steel, and slabs",
      "Bulk commercial contracting with fast site mobilization across Chennai",
    ],
    specsTable: [
      { label: "Primary Fall Net", value: "100mm x 100mm Knotted Polypropylene (4.0mm Cord)" },
      { label: "Debris Overlay Mesh", value: "1mm - 2mm High-Density Monofilament Shade Mesh" },
      { label: "Catch Load Rating", value: "Tested up to 350 kg kinetic impact load" },
      { label: "Standard Compliance", value: "IS 5175 / EN 1263-1 Fall Arrest Standards" },
      { label: "Border Rope", value: "12mm High-Tenacity Braided Poly Boundary Line" },
      { label: "Flame Retardancy", value: "Treated self-extinguishing polymer compound" },
      { label: "UV Classification", value: "Heavy Industrial Outdoor Rating" },
      { label: "Certification", value: "Batch Test Certificate supplied with every order" },
    ],
    faqs: generateFAQsForService("Construction Safety Nets", "safety-nets"),
  },

  "duct-area-safety-nets": {
    slug: "duct-area-safety-nets",
    name: "Duct Area Safety Nets",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Duct Area & Building Shaft Safety Nets | Ram Enterprises Chennai",
    description: "Seal open ventilation shafts and plumbing voids in apartment complexes against bird infestations, falling items, and pest accumulation in Chennai.",
    longDescription: "Open building duct shafts and plumbing voids in apartment complexes provide prime nesting territory for pigeons, leading to foul droppings, trapped dead birds, and pest infestations. Ram Enterprises seals open shaft spaces with long-lasting duct safety nets that allow full plumbing maintenance access while permanently barring pests.",
    aiOverview: "Ram Enterprises Duct Area Safety Nets enclose internal ventilation shafts and plumbing voids, preventing bird nesting, hygiene hazards, and falling debris.",
    image: "/images/main-images/Duct-Area-3.jpg",
    supportingImages: [
      "/images/main-images/Duct-Area-3.jpg",
      "/images/hero/pigeonnet.jpg",
      "/images/materials/FactoryNets.jpeg",
      "/images/hero/safetynets2.jpg",
    ],
    gallery: [
      "/images/main-images/Duct-Area-3.jpg",
      "/images/main-images/Duct-Area-3.jpg",
      "/images/hero/pigeonnet.jpg",
      "/images/materials/FactoryNets.jpeg",
      "/images/hero/safetynets2.jpg",
      "/images/materials/Balconynetwork.jpeg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/main-images/Duct-Area-3.jpg",
    benefits: [
      "Completely seals massive vertical building voids against pigeon colonization",
      "Prevents dropped maintenance tools and trash from falling down the shaft",
      "Preserves 100% building ventilation and natural airflow across bathroom vents",
      "Technicians are rope-access certified for difficult multi-story vertical rigging",
      "Non-corrosive anchors ensure no damage to plumbing runs or shaft concrete",
      "Backed by a 5-Year Replacement Warranty for housing societies and RWAs",
    ],
    specsTable: [
      { label: "Mesh Pitch", value: "30mm x 30mm Square Knotted Mesh" },
      { label: "Material Composition", value: "Virgin UV-Stabilized High-Density Polymer" },
      { label: "Tensile Resilience", value: "140+ kg per mesh intersection point" },
      { label: "Anchoring Scheme", value: "Stainless Steel Fasteners with Perimeter Rigging" },
      { label: "Accessibility", value: "Includes zippered access hatches for plumber servicing" },
      { label: "Fire Resistance", value: "High Ignition Point Synthetic Polymer" },
      { label: "Lifespan", value: "8 to 12 Years inside vertical light wells" },
      { label: "Warranty Term", value: "5 Years Full Society Warranty" },
    ],
    faqs: generateFAQsForService("Duct Area Safety Nets", "safety-nets"),
  },

  "anti-bird-spikes": {
    slug: "anti-bird-spikes",
    name: "Anti-Bird Spikes",
    category: "safety-nets",
    categoryName: "Safety Nets",
    title: "Anti-Bird Spikes Installation in Chennai | Ram Enterprises",
    description: "Humane, stainless steel bird deterrent spikes for AC outdoor units, narrow window ledges, parapet walls, and signboards across Chennai.",
    longDescription: "Where safety nets cannot be anchored, Ram Enterprises installs premium anti-bird spikes. Fabricated with UV-stabilized virgin polycarbonate bases and SS304 marine stainless steel blunt-tip rods, our spikes prevent pigeons and crows from landing without causing them physical injury.",
    aiOverview: "Ram Enterprises Anti-Bird Spikes deliver humane, discreet bird landing deterrents for air conditioners, parapet walls, signboards, and narrow architectural ledges.",
    image: "/images/hero/service-spikes.jpg",
    supportingImages: [
      "/images/hero/pigeonnet.jpg",
      "/images/hero/pigeonnet.jpg",
      "/images/materials/Materials7.jpeg",
      "/images/hero/safetynets2.jpg",
    ],
    gallery: [
      "/images/hero/service-spikes.jpg",
      "/images/hero/pigeonnet.jpg",
      "/images/hero/pigeonnet.jpg",
      "/images/materials/Materials7.jpeg",
      "/images/hero/safetynets2.jpg",
      "/images/materials/Balconynetwork.jpeg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/hero/service-spikes.jpg",
    benefits: [
      "100% humane blunt-tipped design deters birds without physical injury",
      "SS304 marine stainless steel rods completely immune to coastal rust",
      "Flexible UV-stabilized polycarbonate base conforms to curved or flat ledges",
      "Ideal for narrow AC outdoor tops, parapets, roof eaves, and signboards",
      "Zero maintenance required — unaffected by bird droppings or rain",
      "Backed by Ram Enterprises 5-Year Anti-Corrosion Guarantee",
    ],
    specsTable: [
      { label: "Rod Metallurgy", value: "SS304 Marine Stainless Steel (Blunt Safety Tips)" },
      { label: "Base Composition", value: "100% Virgin UV-Stabilized Polycarbonate" },
      { label: "Spike Density", value: "32 to 40 Spikes per Foot (Multi-Angle Fan Spread)" },
      { label: "Strip Length", value: "12 Inches (30 cm) Interlocking Modular Strips" },
      { label: "Installation Method", value: "Industrial Silicone Adhesive / Stainless Screws" },
      { label: "Humane Status", value: "Certified 100% Animal Welfare Compliant" },
      { label: "Corrosion Rating", value: "Zero Rusting in coastal marine atmospheres" },
      { label: "Warranty Period", value: "5 Years Direct Replacement Guarantee" },
    ],
    faqs: generateFAQsForService("Anti-Bird Spikes", "safety-nets"),
  },

  // ----------------------------------------------------
  // Invisible Grills (5 Services)
  // ----------------------------------------------------
  "balcony-invisible-grills": {
    slug: "balcony-invisible-grills",
    name: "Balcony Invisible Grills",
    category: "invisible-grills",
    categoryName: "Invisible Grills",
    title: "Balcony Invisible Grills in Chennai | Ram Enterprises",
    description: "Replace bulky, dark iron bars with modern SS316 marine-grade invisible wire grills. Unrivaled high-rise safety and 180° panoramic views for Chennai homes.",
    longDescription: "Replace heavy, cage-like iron bars with state-of-the-art invisible grills from Ram Enterprises. Using 2.0mm to 3.0mm high-tensile SS316 marine stainless steel cables wrapped in protective transparent nylon sheathing, our invisible grills provide unmatched fall security for children and pets while preserving an unobstructed panoramic vista.",
    aiOverview: "Ram Enterprises Balcony Invisible Grills feature high-tensile SS316 marine stainless steel cables anchored in anodized aluminium tracks, delivering high-rise safety with unblocked views.",
    image: "/images/main-images/Balcony-Grills.jpg",
    supportingImages: [
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/services/shyamchildreninvisiblegrills.jpg",
    ],
    gallery: [
      "/images/main-images/Balcony-Grills.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/services/shyamchildreninvisiblegrills.jpg",
      "/images/services/Shayamstaircase-grills.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/services/shyambalconygrills.jpg",
    benefits: [
      "Marine SS316 stainless cables with 400+ kg breaking force per line",
      "Transparent DuPont nylon sheathing protects hands and prevents fraying",
      "Preserves an unobstructed 180° scenic view and abundant natural breeze",
      "Structural grade T6 powder-coated aluminium tracks that never rust",
      "Tamper-proof internal lock-bush engineering ensures permanent tension",
      "Includes an official 10+ Year Anti-Rust & Tension Assurance Guarantee",
    ],
    specsTable: [
      { label: "Cable Metallurgy", value: "SS316 Marine Grade Multi-Strand Stainless (7x7)" },
      { label: "Wire Outer Diameter", value: "2.0mm / 2.5mm / 3.0mm with DuPont Nylon Coat" },
      { label: "Tensile Breaking Force", value: "400+ kg per individual wire strand" },
      { label: "Standard Cable Pitch", value: "50mm (2 Inches) or 75mm (3 Inches) options" },
      { label: "Mounting Profile", value: "Heavy T6 Anodized & Powder-Coated Aluminium Track" },
      { label: "Corrosion Proofing", value: "100% Saline Rust-Proof (Marine Coastal Grade)" },
      { label: "Emergency Egress", value: "Can be cut with rescue wire cutters during emergencies" },
      { label: "Warranty Coverage", value: "10+ Years Anti-Rust & Structural Tension Guarantee" },
    ],
    faqs: generateFAQsForService("Balcony Invisible Grills", "invisible-grills"),
  },

  "children-invisible-grills": {
    slug: "children-invisible-grills",
    name: "Children Invisible Grills",
    category: "invisible-grills",
    categoryName: "Invisible Grills",
    title: "Children Invisible Grills for Balconies & Windows | Ram Enterprises Chennai",
    description: "High-density 2-inch spaced SS316 invisible safety grills preventing toddlers and children from slipping through balconies or windows in Chennai.",
    longDescription: "Safeguard young children in high-rise towers with Ram Enterprises child-safety invisible grills. Configured with an extra-tight 2-inch cable pitch, these marine stainless steel wire grills prevent curious toddlers from slipping through railings while maintaining a bright, airy, and contemporary interior atmosphere.",
    aiOverview: "Ram Enterprises Child-Safe Invisible Grills feature high-density 2-inch cable spacing, preventing toddler slips from high-rise balconies with SS316 marine-grade stainless cables.",
    image: "/images/services/shyamchildreninvisiblegrills.jpg",
    supportingImages: [
      "/images/hero/childrensafetygrill.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/services/shyambalconygrills.jpg",
    ],
    gallery: [
      "/images/services/shyamchildreninvisiblegrills.jpg",
      "/images/hero/childrensafetygrill.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/main-images/Balcony-Grills.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/services/shyamchildreninvisiblegrills.jpg",
    benefits: [
      "Tight 50mm (2-inch) cable spacing prevents toddler heads or limbs from passing",
      "Each cable withstands over 400kg load, exceeding child safety standards",
      "Smooth nylon sheathing eliminates sharp edges, preventing accidental cuts",
      "No cage-like prison feeling — preserves natural sunlight and breeze",
      "Heavy-duty anchored base tracks withstand extreme jumping impact",
      "10+ Year Workmanship & Tension Guarantee for high-rise families",
    ],
    specsTable: [
      { label: "Cable Pitch (Spacing)", value: "50mm (2 Inches) High-Density Childproof Spacing" },
      { label: "Cable Specification", value: "SS316 Marine Stainless Steel (7x7 Braided)" },
      { label: "Protective Layer", value: "Transparent DuPont Nylon Extrusion (Non-Toxic)" },
      { label: "Breaking Load", value: "400+ kg tensile limit per wire line" },
      { label: "Base Track", value: "Extruded Aluminium Alloy T6 (1.5mm Thickness)" },
      { label: "Fasteners", value: "SS304 Heavy Expansion Concrete Sleeve Anchors" },
      { label: "Visual Clarity", value: "98% Optical Transparency from 2 meters away" },
      { label: "Warranty", value: "10+ Years Direct Replacement & Tension Guarantee" },
    ],
    faqs: generateFAQsForService("Children Invisible Grills", "invisible-grills"),
  },

  "pet-invisible-grills": {
    slug: "pet-invisible-grills",
    name: "Pet-Safe Invisible Grills",
    category: "invisible-grills",
    categoryName: "Invisible Grills",
    title: "Pet-Safe Invisible Grills | Ram Enterprises Chennai",
    description: "Bite-proof, chew-resistant SS316 marine stainless invisible grills for homes with curious cats and active dogs across Chennai.",
    longDescription: "Keep your playful pets completely secure on high-rise balconies with Ram Enterprises pet invisible grills. Made from high-tensile SS316 marine stainless steel wires that cannot be chewed through, scratched, or pushed aside, they allow pets to enjoy outdoor sights safely without fear of high-altitude falls.",
    aiOverview: "Ram Enterprises Pet Invisible Grills provide chew-proof, high-tension SS316 cable protection, ensuring active cats and dogs cannot leap or slip off high-rise balconies.",
    image: "/images/services/shyampetinvisiblegrills.jpg",
    supportingImages: [
      "/images/hero/pet.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/main-images/Balcony-Grills.jpg",
    ],
    gallery: [
      "/images/services/shyampetinvisiblegrills.jpg",
      "/images/hero/pet.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyamchildreninvisiblegrills.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/services/shyampetinvisiblegrills.jpg",
    benefits: [
      "SS316 marine wire core is completely immune to pet chewing and biting",
      "Claw-proof transparent nylon coating will not peel, rip, or discolor",
      "Tight 50mm cable spacing prevents curious cats and small puppies from escaping",
      "Eliminates balcony cage look while providing impenetrable containment",
      "Non-corrosive aluminium guide rails endure all outdoor weather conditions",
      "Backed by Ram Enterprises 10+ Year Pet Protection Guarantee",
    ],
    specsTable: [
      { label: "Cable Metallurgy", value: "SS316 Marine Stainless (Chew-Proof Core)" },
      { label: "Coating Type", value: "High-Density Abrasion-Resistant Clear Nylon" },
      { label: "Cable Spacing", value: "50mm (2 Inches) Escape-Proof Pitch" },
      { label: "Tensile Capacity", value: "400+ kg force per line (Impervious to pet weight)" },
      { label: "Profile Track", value: "T6 High-Strength Powder-Coated Aluminium" },
      { label: "Toxicity Rating", value: "100% Pet-Safe and Non-Toxic Formulation" },
      { label: "Coastal Endurance", value: "100% Rust-Free in coastal saline climates" },
      { label: "Warranty Period", value: "10+ Years Anti-Chew & Anti-Rust Guarantee" },
    ],
    faqs: generateFAQsForService("Pet-Safe Invisible Grills", "invisible-grills"),
  },

  "window-invisible-grills": {
    slug: "window-invisible-grills",
    name: "Window Invisible Grills",
    category: "invisible-grills",
    categoryName: "Invisible Grills",
    title: "Window Invisible Grills in Chennai | Ram Enterprises",
    description: "Upgrade dark window bars with sleek SS316 invisible window grills. Enjoy panoramic window views, burglar deterrence, and fresh air flow in Chennai.",
    longDescription: "Transform dark, blocked windows with modern invisible window grills from Ram Enterprises. Anchored firmly into window lintels with powder-coated aluminium profiles, our stainless steel wire grills provide robust fall prevention and intruder deterrence while flooding your rooms with light and fresh breeze.",
    aiOverview: "Ram Enterprises Window Invisible Grills replace bulky metal window bars with sleek SS316 stainless cables, delivering safety without sacrificing natural ventilation.",
    image: "/images/hero/windowgrill.webp",
    supportingImages: [
      "/images/hero/windowgrill.webp",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/hero/customgrill.jpg",
    ],
    gallery: [
      "/images/hero/windowgrill.webp",
      "/images/hero/windowgrill.webp",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/hero/customgrill.jpg",
      "/images/services/shyamchildreninvisiblegrills.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/hero/windowgrill.webp",
    benefits: [
      "Eliminates gloomy prison-like window bars, maximizing interior sunlight",
      "Horizontal or vertical wire alignment options tailored to your window frame",
      "Multi-strand SS316 marine steel cables withstand over 400kg per line",
      "Seamless integration with sliding UPVC, aluminium, or wooden window frames",
      "Zero repainting required — will never rust or flake in coastal humidity",
      "Official 10+ Year Replacement Guarantee on all window installations",
    ],
    specsTable: [
      { label: "Wire Construction", value: "SS316 Grade Stainless Cable Core (7x7 Braided)" },
      { label: "Outer Thickness", value: "2.0mm / 2.5mm Transparent Nylon Coated" },
      { label: "Tensile Strength", value: "400+ kg breaking force threshold" },
      { label: "Track System", value: "T6 Architectural Aluminium Mounting Extrusions" },
      { label: "Orientation", value: "Vertical or Horizontal Cable Configuration" },
      { label: "Spacing Options", value: "50mm (2 Inches) or 75mm (3 Inches)" },
      { label: "Window Compatibility", value: "UPVC, Aluminium, Wooden & Concrete Openings" },
      { label: "Warranty Term", value: "10+ Years Anti-Rust & Cable Stability Guarantee" },
    ],
    faqs: generateFAQsForService("Window Invisible Grills", "invisible-grills"),
  },

  "staircase-invisible-grills": {
    slug: "staircase-invisible-grills",
    name: "Staircase Invisible Grills",
    category: "invisible-grills",
    categoryName: "Invisible Grills",
    title: "Staircase & Duplex Invisible Grills | Ram Enterprises Chennai",
    description: "Architectural vertical invisible grills for duplex stairwells, open foyers, and mezzanine railings across residential and commercial properties in Chennai.",
    longDescription: "Duplex villas and commercial buildings with open stairwells present serious fall dangers for children and seniors. Ram Enterprises designs custom floor-to-ceiling vertical invisible grills that enclose stair voids elegantly while maintaining an airy, luxurious interior aesthetic.",
    aiOverview: "Ram Enterprises Staircase Invisible Grills deliver floor-to-ceiling SS316 vertical wire enclosures for duplex homes and commercial atriums throughout Chennai.",
    image: "/images/services/Shayamstaircase-grills.jpg",
    supportingImages: [
      "/images/services/Shayamstaircase-grills.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/hero/customgrill.jpg",
    ],
    gallery: [
      "/images/services/Shayamstaircase-grills.jpg",
      "/images/services/Shayamstaircase-grills.jpg",
      "/images/main-images/Balcony-Grills.jpg",
      "/images/services/shyambalconygrills.jpg",
      "/images/hero/customgrill.jpg",
      "/images/main-images/Balcony-Grills.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/services/Shayamstaircase-grills.jpg",
    benefits: [
      "Custom continuous vertical runs up to 30+ feet from floor to ceiling",
      "Eliminates open stairwell void fall risks for kids, elderly, and pets",
      "Modern architectural finish adds luxury appeal to duplex interiors",
      "Ultra-strong SS316 marine cables anchored into ceiling beams and floor slabs",
      "Allows complete illumination and unblocked interior sightlines",
      "Backed by Ram Enterprises 10+ Year Structural Workmanship Guarantee",
    ],
    specsTable: [
      { label: "Cable Metallurgy", value: "SS316 Marine Grade Multi-Strand Stainless (7x7)" },
      { label: "Wire Outer Diameter", value: "2.5mm / 3.0mm with Transparent Nylon Sheath" },
      { label: "Vertical Span", value: "Custom floor-to-ceiling spans up to 35 feet" },
      { label: "Line Pitch", value: "50mm (2 Inches) or 75mm (3 Inches) intervals" },
      { label: "Structural Anchors", value: "Heavy-Duty Expansion Anchor Bolts in Concrete" },
      { label: "Tensile Capacity", value: "400+ kg breaking force per vertical strand" },
      { label: "Aesthetic Profile", value: "Minimalist Architectural Line Design" },
      { label: "Warranty Term", value: "10+ Years Structural & Tension Assurance" },
    ],
    faqs: generateFAQsForService("Staircase Invisible Grills", "invisible-grills"),
  },

  // ----------------------------------------------------
  // Cloth Hangers (3 Services)
  // ----------------------------------------------------
  "ceiling-cloth-hangers": {
    slug: "ceiling-cloth-hangers",
    name: "Ceiling Cloth Hangers",
    category: "cloth-hangers",
    categoryName: "Cloth Drying Systems",
    title: "Ceiling Cloth Drying Hangers in Chennai | Ram Enterprises",
    description: "Space-saving dual-pulley stainless steel ceiling drying systems. Free up 100% balcony floor space with effortless hoist mechanisms in Chennai.",
    longDescription: "Maximize your compact apartment balcony space with premium ceiling cloth drying hangers from Ram Enterprises. Engineered with individual dual-pulley mechanisms and rust-proof SS304 stainless steel pipes, our systems let you lower drying rods effortlessly to chest height and hoist wet laundry up to the ceiling, keeping your balcony floor completely clear.",
    aiOverview: "Ram Enterprises Ceiling Cloth Hangers feature smooth nylon pulley systems with rust-proof stainless steel pipes, maximizing drying space in apartment balconies across Chennai.",
    image: "/images/main-images/cloth-Hangers3.jpg",
    supportingImages: [
      "/images/main-images/clothhanger-work.jpg",
      "/images/main-images/clothhangerwork2.jpg",
      "/images/materials/clothhangerwork.jpeg",
      "/images/main-images/clothhanger-work.jpg",
    ],
    gallery: [
      "/images/main-images/cloth-Hangers3.jpg",
      "/images/main-images/clothhanger-work.jpg",
      "/images/main-images/clothhangerwork2.jpg",
      "/images/materials/clothhangerwork.jpeg",
      "/images/main-images/clothhanger-work.jpg",
      "/images/main-images/clothhangerwork2.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/materials/clothhangerwork.jpeg",
    benefits: [
      "Frees up 100% of balcony floor space compared to bulky folding floor stands",
      "Independently operated rods lower to chest level for effortless loading",
      "High ceiling elevation utilizes natural warm airflow for 2x faster laundry drying",
      "SS304 rustproof stainless steel pipes carry heavy wet blankets and jeans",
      "Ultra-smooth low-friction nylon pulley wheels for whisper-quiet hoisting",
      "Backed by Ram Enterprises 3-Year Operational & Material Guarantee",
    ],
    specsTable: [
      { label: "Pipe Material", value: "SS304 Seamless Rust-Proof Stainless Steel" },
      { label: "Pipe Configuration", value: "4, 6, or 8 Independent Operating Rods" },
      { label: "Rod Lengths Available", value: "4 ft, 5 ft, 6 ft, 7 ft, 8 ft Custom Spans" },
      { label: "Load Capacity per Rod", value: "Up to 8 kg wet laundry per individual pipe" },
      { label: "Pulley Mechanism", value: "Dual-Bearing Nylon Low-Friction Wheels" },
      { label: "Hoist Cord", value: "High-Tensile Braided Tangle-Free Nylon Rope" },
      { label: "Locking Scheme", value: "Wall-Mounted Stainless Locking Cleat Plate" },
      { label: "Warranty Coverage", value: "3 Years Operational & Anti-Rust Warranty" },
    ],
    faqs: generateFAQsForService("Ceiling Cloth Hangers", "cloth-hangers"),
  },

  "balcony-cloth-hangers": {
    slug: "balcony-cloth-hangers",
    name: "Balcony Cloth Hangers",
    category: "cloth-hangers",
    categoryName: "Cloth Drying Systems",
    title: "Balcony Railing Cloth Drying Hangers in Chennai | Ram Enterprises",
    description: "Heavy-duty stainless steel balcony railing and wall-bracket drying systems for efficient, sunlit outdoor laundry drying across Chennai.",
    longDescription: "Tired of unstable folding drying racks blowing over in high winds? Ram Enterprises installs custom balcony railing cloth drying systems manufactured with high-gauge SS304 stainless steel. Positioned to catch optimum sunlight and breeze, they dry large family laundry loads rapidly while preserving your balcony passage.",
    aiOverview: "Ram Enterprises Balcony Cloth Hangers provide sturdy, weather-resistant drying systems anchored directly to balcony railings and side walls for maximum sun exposure.",
    image: "/images/main-images/clothhanger-work.jpg",
    supportingImages: [
      "/images/main-images/clothhangerwork2.jpg",
      "/images/main-images/clothhangerwork2.jpg",
      "/images/materials/clothhangerwork.jpeg",
      "/images/main-images/cloth-Hangers3.jpg",
    ],
    gallery: [
      "/images/main-images/clothhanger-work.jpg",
      "/images/main-images/clothhangerwork2.jpg",
      "/images/main-images/clothhangerwork2.jpg",
      "/images/materials/clothhangerwork.jpeg",
      "/images/main-images/cloth-Hangers3.jpg",
      "/images/main-images/clothhanger-work.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/main-images/clothhangerwork2.jpg",
    benefits: [
      "Sturdy fixed and foldable railing bracket configurations available",
      "Maximizes outdoor sunlight and breeze for rapid drying of heavy garments",
      "SS304 marine stainless steel pipes that will never rust or stain clothes",
      "Wind-proof design prevents clothes and stands from blowing off high floors",
      "Compact footprint leaves your balcony clear for relaxation and plants",
      "3-Year Comprehensive Warranty with zero maintenance requirements",
    ],
    specsTable: [
      { label: "Material Composition", value: "SS304 Food-Grade Rust-Proof Stainless Steel" },
      { label: "Pipe Thickness", value: "Heavy Gauge 0.8mm Wall Thickness Tubes" },
      { label: "Mounting Type", value: "Balcony Railing Clamp / Side-Wall Heavy Brackets" },
      { label: "Total Linear Capacity", value: "24 to 48 Feet of Active Clothes Drying Line" },
      { label: "Weight Rating", value: "Tested for 30+ kg total wet laundry capacity" },
      { label: "Weather Durability", value: "100% Rust-Proof in heavy coastal rains" },
      { label: "Installation Time", value: "1 to 2 Hours complete doorstep mounting" },
      { label: "Warranty Term", value: "3 Years Complete Replacement Warranty" },
    ],
    faqs: generateFAQsForService("Balcony Cloth Hangers", "cloth-hangers"),
  },

  "wall-mounted-cloth-hangers": {
    slug: "wall-mounted-cloth-hangers",
    name: "Wall Mounted Cloth Hangers",
    category: "cloth-hangers",
    categoryName: "Cloth Drying Systems",
    title: "Wall-Mounted Foldable Cloth Drying Racks | Ram Enterprises Chennai",
    description: "Accordion-style collapsible stainless steel wall drying racks. Folds flat against the wall when not in use for Chennai utility spaces.",
    longDescription: "Eliminate messy drying stands with accordion-style wall mounted cloth drying racks from Ram Enterprises. Crafted from 100% rustproof SS304 stainless steel, these racks extend outwards smoothly during laundry time and fold completely flat against your wall when dry, creating an uncluttered living environment.",
    aiOverview: "Ram Enterprises Wall Mounted Cloth Hangers feature collapsible accordion stainless steel mechanisms that fold flat against the wall, optimizing compact utility zones across Chennai.",
    image: "/images/main-images/clothhangerwork2.jpg",
    supportingImages: [
      "/images/main-images/cloth-Hangers3.jpg",
      "/images/materials/clothhangerwork.jpeg",
      "/images/main-images/clothhangerwork2.jpg",
      "/images/main-images/clothhanger-work.jpg",
    ],
    gallery: [
      "/images/main-images/clothhangerwork2.jpg",
      "/images/main-images/cloth-Hangers3.jpg",
      "/images/materials/clothhangerwork.jpeg",
      "/images/main-images/clothhangerwork2.jpg",
      "/images/main-images/clothhanger-work.jpg",
      "/images/main-images/clothhanger-work.jpg",
    ],
    beforeImage: "/images/gallery/before_balcony.png",
    afterImage: "/images/materials/clothhangerwork.jpeg",
    benefits: [
      "Accordion folding design collapses flush against the wall in seconds",
      "Perfect for narrow utility passages, laundry rooms, and indoor balconies",
      "SS304 stainless steel construction holds heavy wet bedsheets and jeans",
      "Smooth scissor-rivet joints allow effortless one-handed expansion",
      "Zero floor footprint ensures full walking space in utility rooms",
      "Supported by Ram Enterprises 3-Year Anti-Rust Warranty",
    ],
    specsTable: [
      { label: "Material Grade", value: "100% SS304 Heavy-Duty Stainless Steel" },
      { label: "Expansion Mechanism", value: "Accordion Multi-Rivet Collapsible Arms" },
      { label: "Open / Closed Depth", value: "Extends to 24 inches / Folds flat to 2 inches" },
      { label: "Width Options", value: "3 ft, 4 ft, 5 ft, 6 ft Width Configurations" },
      { label: "Rod Count", value: "5 to 7 Heavy Stainless Cross-Pipes" },
      { label: "Load Capacity", value: "Up to 25 kg distributed wet laundry load" },
      { label: "Wall Anchor Type", value: "SS304 Expansion Screws into solid brick/concrete" },
      { label: "Warranty Coverage", value: "3 Years Operational & Rust Guarantee" },
    ],
    faqs: generateFAQsForService("Wall Mounted Cloth Hangers", "cloth-hangers"),
  },
};
